USE [master]
GO
CREATE LOGIN [DOMAIN\SqlSysAdmins] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [DOMAIN\SqlSysAdmins]
GO


USE [master]
GO
CREATE LOGIN [DOMAIN\SqlAuditAdmins] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [DOMAIN\SqlAuditAdmins]
GO


USE [master]
GO
CREATE LOGIN [DOMAIN\SqlAudit] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [DOMAIN\SqlAudit]
GO

